[package]
name = "browncode"
version = "0.1.0"
authors = ["Liam Pribis <jackpribis@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
peg = { version = "0.5" }

[dependencies]
peg = "0.5"
sdl2 = "0.32"
lazy_static = "1.4"
structopt = "0.3"
rand = "0.7"