[package]
name = "browncode"
version = "0.1.0"
authors = ["Liam Pribis <jackpribis@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
peg = { version = "0.5.7" }

[dependencies]
peg = "0.5.7"
lazy_static = "1.4.0"
